CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_POINTING=y
CONFIG_DONGLE_SCREEN_WPM_ACTIVE=n
CONFIG_DONGLE_SCREEN_IDLE_TIMEOUT_S=0

# Keep display rendering below BLE and keyboard processing priority.
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=10
